# Generated by Django 4.1.3 on 2023-08-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitrator', '0002_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuhours',
            name='store_id',
        ),
        migrations.AddField(
            model_name='menuhours',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitrator.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timezone',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitrator.store'),
        ),
    ]
