# Generated by Django 4.1.3 on 2023-08-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitrator', '0003_store_remove_menuhours_store_id_menuhours_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('timestamp_utc', models.DateTimeField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitrator.store')),
            ],
        ),
    ]
