# Generated by Django 4.1.3 on 2023-08-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitrator', '0005_remove_storestatus_id_alter_storestatus_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime_last_hour', models.FloatField()),
                ('uptime_last_day', models.FloatField()),
                ('uptime_last_week', models.FloatField()),
                ('downtime_last_hour', models.FloatField()),
                ('downtime_last_day', models.FloatField()),
                ('downtime_last_week', models.FloatField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitrator.store')),
            ],
        ),
    ]
