# Generated by Django 4.1.3 on 2023-08-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitrator', '0006_storemetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
